### ISSUE TITLE
Type error on split tags

### ISSUE THREAD

**Issue by bulju** [davidji99/terraform-provider-split#114]
Hi there,

I'm facing issues when importing `split_split`, when the split has tags.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### HerokuX Provider Version

```
Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/davidji99/split v0.6.2
+ provider registry.terraform.io/hashicorp/aws v4.8.0
```
> Note: I've tested with split v0.7.0, and I'm getting another error, and I will also put a solution in place for that.

### Affected Resource(s)
- split_split

### Terraform Configuration Files
```hcl
resource "split_split" "this" {
  for_each        = var.splits
  workspace_id    = each.value.workspace
  traffic_type_id = each.value.traffic_type
  name            = each.value.name
  description     = each.value.description
}

splits = {
  1 = {
    name          = "name"
    description   = "description"
    workspace     = "workspace_id"
    traffic_type  = "traffic_type_id"
  },

  2 = {
    name          = "name"
    description   = "description"
    workspace     = "workspace_id"
    traffic_type  = "traffic_type_id"
  },
}
```

### Expected Behavior
What should have happened?
The split should be imported

### Actual Behavior
What actually happened?
Terraform crashed because of a type error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a split containing tags
1. Create the terraform code to import it
1. `terraform import <resource_name> <workspace_id>:<split_id> `

### Important mentions

[Tags is being defined as a list of strings](https://github.com/davidji99/terraform-provider-split/blob/f4f97c46f5bd0ae10ec8f294fa30188560a1e33a/api/split.go#L21), but the response from the API is returning a list of key/value, as I detail:
```bash
> curl -X GET \
  -H 'Content-Type:application/json' \
  -H 'Authorization: Bearer <redacted>' \
  https://api.split.io/internal/api/v2/splits/ws/<redacted>/<redacted>
{"id":"<redacted>","name":<redacted>","description":"<redacted>","trafficType":{"id":"<redacted>","name":"<redacted>"},"creationTime":1604662508084,"tags":[{"name":"<redacted>"}],"owners":[{"id":"<redacted>","type":"<redacted>"},{"id":"<redacted>","type":"<redacted>"}]}%  
```

**Comment by bulju** [comment]
Hi @davidji99 , I'll work on a solution for this, and also add a missing check in [checkRateLimit](https://github.com/davidji99/terraform-provider-split/blob/f4f97c46f5bd0ae10ec8f294fa30188560a1e33a/api/api.go#L143), which should check if response.statusCode is not empty (I got invalid memory address or nil pointer dereference)
Probably tomorrow I'll raise a PR about this 😄

**Comment by davidji99** [comment]
Thanks!
