### ISSUE TITLE
[?] Is it intentional that API client-side and server-side keys are created along with an environment?

### ISSUE THREAD

**Issue by dbaggott** [davidji99/terraform-provider-split#199]
When creating an environment with tf code like:

```
data "split_workspace" "default" {
  name = "Default"
}

resource "split_environment" "environment" {
  name         = var.name
  production   = var.is_production
  workspace_id = data.split_workspace.default.id
}
```

Both server-side and client-side API keys are automatically created.

The existence of these automatically created keys prevents the environment from being automatically deleted during destroy.

Is this an intentional part of the resource or split.io server-side behavior that cannot be avoided?

**Comment by davidji99** [comment]
Hey @dbaggott,

This question would best be served asking Split support. The provider doesn't do anything with creating API keys when creating a `split_environment` resource. Plus, https://docs.split.io/reference/create-environment doesn't indicate explicitly that API keys are created as a result of creating an environment.
