### ISSUE TITLE
New resource: split_traffic_type_attribute

### ISSUE THREAD

**Issue by davidji99** [davidji99/terraform-provider-split#4]
https://help.split.io/hc/en-us/articles/360016744791-What-are-Attributes-in-the-Admin-API-vs-Custom-Attributes-in-Targeting-Rules-

**Comment by davidji99** [comment]
There is only a `GET` endpoint for traffic types so I cannot implement a full resource.

**Comment by dtk-DaveKarow** [comment]
Link to the Split Admin API docs where it documents that Traffic types are read-only from the Admin API but can be set inside the app by Split Admins: https://docs.split.io/reference/traffic-types-overview.  Not sure why this is the case, but I'll ask the Split API folks for you!

**Comment by dtk-DaveKarow** [comment]
Good news.  I checked with the PM and this limitation is now gone: Traffic types **can** now be created via the Admin API. It's in production now, but behind a release flag. Public release is pending a doc update.  I'll update you when that's handled.
