### ISSUE TITLE
Doc Bug - split_workspace data source not documented

### ISSUE THREAD

**Issue by kleinjoshuaa** [davidji99/terraform-provider-split#67]
Hi there,

I'm really excited to be playing around with the Split Terraform provider. I'd just like to make a quick note that it looks like in the documentation the data source `split_workspace` is not documented anywhere, and some of the code examples use `data split_environment` when they should be using `data split_workspace` Such as this file [here](https://github.com/davidji99/terraform-provider-split/blob/master/docs/data-sources/workspace.md) or this file [here](https://github.com/davidji99/terraform-provider-split/blob/master/docs/resources/environment.md) or this one [as well](https://github.com/davidji99/terraform-provider-split/blob/master/docs/resources/segment.md)

Again - really excited to see your hard work and thank you for what you've done so far.

**Comment by davidji99** [comment]
Ah, good callout. Will fix!
